DROP TABLE IF EXISTS CAR;
CREATE TABLE CAR (
	id serial NOT NULL,
	issued_to_id	INTEGER NOT NULL, FOREIGN KEY (issued_to_id) REFERENCES Users (index),
	issued_on	date not null default NOW(),
	issued_by_id	INTEGER NOT NULL, FOREIGN KEY (issued_by_id) REFERENCES Users (index),
	reply_by	date not null default NOW(),
	docket			INTEGER,
	company_id		INTEGER, FOREIGN KEY (company_id) REFERENCES Company (Index),
	problem		text,
	cause		text,
	action		text,
	effectiveness		text,
	presses		text,
	part1_user_id	INTEGER, FOREIGN KEY (part1_user_id) REFERENCES Users (index),
	part1_signed_on	date,
	part2_user_id	INTEGER, FOREIGN KEY (part2_user_id) REFERENCES Users (index),
	part2_signed_on	date,
	part3_user_id	INTEGER, FOREIGN KEY (part3_user_id) REFERENCES Users (index),
	part3_signed_on	date,
	part4_user_id	INTEGER, FOREIGN KEY (part3_user_id) REFERENCES Users (index),
	part4_signed_on	date,
	reprint			text,
	reprint_approval	text,
	artwork			text,
	reprint_on	date,
	approved_by_id	INTEGER, FOREIGN KEY (approved_by_id) REFERENCES Users (index),
	approved_on		date,

	created_on	timestamp with time zone NOT NULL default NOW(),
	updated_on	timestamp with time zone NOT NULL default NOW(),
	deleted		boolean default false,
	area		TEXT,
	reason		TEXT,
	PRIMARY KEY (id)
);
