DROP TABLE IF EXISTS Companies;

CREATE TABLE Companies (
	id SERIAL NOT NULL,
	ysnSupplier		CHAR(1) default 'N',
	ysnReseller		CHAR(1) default 'N',
	strAccountNum	TEXT,
	name			TEXT NOT NULL,
	address1		TEXT,
	address2		TEXT,
	city			TEXT,
	state	TEXT,
	strPostalCode	TEXT,
	Country		TEXT,
	Phone		TEXT,
	strExt			TEXT,
	Fax			TEXT,
	statetaxNumber	TEXT,	
	fedtaxNumber	TEXT,
	ysnGSTExempt		char(1) default 'N',
	ysnPSTExempt		char(1) default 'N',
	LegalForm	 		TEXT,
	strPrintExpenditure	TEXT,
	strPurchaseDate		TEXT,
	strLegalBusName		TEXT,
	strBusinessType		TEXT,
	strBusinessNature	TEXT,
	dtmBusinessStartdate date,
	strPresidentOwner	TEXT,
	strEmployees		TEXT,
	strAnnualSales		TEXT,
	strBankName			TEXT,
	strBankBranch		TEXT,
	strBankAccountNo	TEXT,
	strBankAccountManager	TEXT,
	strBankPhone		TEXT,
	strBankFax			TEXT,
	strBankEmail			TEXT,
	lngPriceList			INT4,
	dblPricingPercent		numeric(16,4) DEFAULT '0.0000' NOT NULL,
	salesrep_id			INTEGER, 
/* FOREIGN KEY will be added in users after the addition of that table 
FOREIGN KEY (Salesrep_id) REFERENCES Users (id),
*/
	created_on			timestamp with time zone NOT NULL default NOW(),
	updated_on			timestamp with time zone NOT NULL default NOW(),
	LastLoggedIn			timestamp with time zone,
	currency_id		INTEGER, FOREIGN KEY (currency_id) REFERENCES Currencies (id),
	ysnAccountActivation	CHAR(1) DEFAULT 'N' NOT NULL,
	strCustomGreeting		TEXT,
	strWebURL				TEXT,
	ysnMailingList			CHAR(1) DEFAULT 'N' NOT NULL,
	quote_project_breakdown	CHAR(1) DEFAULT 'N',
	PRIMARY KEY (id)
);
