DROP TABLE IF EXISTS Companies;

CREATE TABLE Companies (
	id SERIAL NOT NULL,
	ysnSupplier		CHAR(1) default 'N',
	ysnReseller		CHAR(1) default 'N',
	strAccountNum	TEXT,
	name			TEXT NOT NULL,
	address1		TEXT,
	address2		TEXT,
	city			TEXT,
	state	TEXT,
	postalcode	TEXT,
	Country		TEXT,
	Phone		TEXT,
	strExt			TEXT,
	Fax			TEXT,
	statetaxNumber	TEXT,	
	fedtaxNumber	TEXT,
	ysnGSTExempt		char(1) default 'N',
	ysnPSTExempt		char(1) default 'N',
	business_form	 		TEXT,
	strPrintExpenditure	TEXT,
	strPurchaseDate		TEXT,
	business_name		TEXT,
	business_type		TEXT,
	established 		date,
	president_owner		TEXT,
	employees		TEXT,
	annual_sales		TEXT,
	bank_name			TEXT,
	bank_branch		TEXT,
	bank_account	TEXT,
	bank_manager	TEXT,
	bank_phone		TEXT,
	bank_fax			TEXT,
	bank_email			TEXT,
	priceList_id			INT4,
	discount		numeric(16,4) DEFAULT '0.0000' NOT NULL,
	salesrep_id			INTEGER, 
/* FOREIGN KEY will be added in users after the addition of that table 
FOREIGN KEY (Salesrep_id) REFERENCES Users (id),
*/
	created_on			timestamp with time zone NOT NULL default NOW(),
	updated_on			timestamp with time zone NOT NULL default NOW(),
	currency_id		INTEGER, FOREIGN KEY (currency_id) REFERENCES Currencies (id),
	ysnAccountActivation	CHAR(1) DEFAULT 'N' NOT NULL,
	greeting		TEXT,
	url				TEXT,
	mailinglist			CHAR(1) DEFAULT 'N' NOT NULL,
	quote_project_breakdown	CHAR(1) DEFAULT 'N',
	detail_level			integer,
	notes					text,
	deleted					BOOLEAN NOT NULL default false,
	PRIMARY KEY (id)
);
