
CREATE SEQUENCE Paper_id_seq;

CREATE TABLE Papers (
	id			INTEGER NOT NULL default nextval('Paper_id_seq'),
	owner_id	INTEGER NOT NULL, FOREIGN KEY (owner_id) REFERENCES Companies (id),
	manufacturer_id	INTEGER NOT NULL, FOREIGN KEY (manufacturer_id) REFERENCES Manufacturers (id),
	brand_id		INTEGER NOT NULL, FOREIGN KEY (brand_id) REFERENCES StockBrands (id),
	finish_id	INTEGER NOT NULL, FOREIGN KEY (finish_id) REFERENCES StockFinishes (id),
	colour_id	INTEGER NOT NULL, FOREIGN KEY (colour_id) REFERENCES StockColours (id),
	weight_id	INTEGER NOT NULL, FOREIGN KEY (weight_id) REFERENCES StockWeights (id),
	quality_id	INTEGER NOT NULL, FOREIGN KEY (quality_id) REFERENCES StockQualities (id),
	cuttable	boolean NOT NULL default true,
	doublesided	boolean	NOT NULL default true,
	perfecting	boolean NOT NULL default false,
	taxexempt1	boolean NOT NULL default false,
	taxexempt2	boolean NOT NULL default false,
	multipart	boolean NOT NULL default false,
	score_required	boolean NOT NULL default false,
	die_score_required	BOOLEAN NOT NULL default false,
	calliper	NUMERIC(10,4),
	width		float,
	height		float,
	mweight		float,
	gsm			float,
	basis_width	float,
	basis_height	float,
	blade_cleaning	boolean,
	grain_direction	text,
	grade			integer,	
	fsc_code		text,
	message			text,
	parts			integer,
	in_stock		INTEGER,
	allocated		INTEGER,
	user_type		char(1),
	PRIMARY KEY (id)
);
