
CREATE TABLE PurchaseOrders (
	id	SERIAL NOT NULL,
	num			TEXT,
	currency_id	INTEGER, FOREIGN KEY (currency_id) REFERENCES Currencies (id),
	company_id	INTEGER, FOREIGN KEY (company_id) REFERENCES Companies (id),
	supplier_id	INTEGER, FOREIGN KEY (supplier_id) REFERENCES Companies (id),
	contact_id	INTEGER, FOREIGN KEY (contact_id) REFERENCES Users (id),
	total		float,
	created_by	INTEGER, FOREIGN KEY (created_by) REFERENCES Users (id),
	created_on	TIMESTAMP WITH TIME ZONE NOT NULL default NOW(),
	updated_on	TIMESTAMP WITH TIME ZONE NOT NULL default NOW(),
	subtotal	float,
	authorized_by	INTEGER, FOREIGN KEY (authorized_by) REFERENCES Users (id),
	authorized_on	TIMESTAMP WITH TIME ZONE,
	authorized BOOLEAN,
	delivered_on	TIMESTAMP WITH TIME ZONE,
	delivered_on_switch	TEXT,
	deleted		BOOLEAN NOT NULL default false,
	shipping_terms	TEXT,
	shipping_method	TEXT,
	vendor_contact		text,
	vendor_name			text,
	vendor_address1		text,
	vendor_address2		text,
	vendor_city			text,
	vendor_country		text,
	vendor_state		text,
	vendor_postalcode	text,
	vendor_phone		text,
	vendor_fax			text,
	vendor_sms			text,
	vendor_email		text,
	shipto_name			text,
	shipto_contact		TEXT,
	shipto_address1		text,
	shipto_address2		text,
	shipto_city			text,
	shipto_country		text,
	shipto_state		text,
	shipto_postalcode	text,
	shipto_phone		text,
	shipto_mobile		text,
	shipto_fax			text,
	shipto_sms			text,
	shipto_email		text,
	manifest_id			INTEGER,
	cancelled			BOOLEAN NOT NULL default false,
	PRIMARY KEY (id)
);

CREATE TABLE PurchaseOrder_Notifications (
	po_id	INTEGER NOT NULL, FOREIGN KEY (po_id) REFERENCES PurchaseOrders (id),
	user_id	INTEGER NOT NULL, FOREIGN KEY (user_id) REFERENCES Users (id),
	PRIMARY KEY (po_id, user_id)
);

CREATE TABLE PurchaseOrder_Logs (
	id		SERIAL NOT NULL,
	po_id	INTEGER NOT NULL, FOREIGN KEY (po_id) REFERENCES PurchaseOrders (id),
	user_id	INTEGER NOT NULL, FOREIGN KEY (user_id) REFERENCES Users (id),
	created_on	timestamp with time zone default NOW(),	
	reason		TEXT,
	PRIMARY KEY (id)
);
