%Config = (
	port			=>	10514,
	pid_file		=>	'/run/openprint-syslog.pid',
	from			=>	'iconnor@point-one.com',
	recipient	 =>	'iconnor@point-one.com',
	smtp-server	=>	'localhost',
	skin_path	 =>	'/var/www/PointOne Graphics Inc/',
	document_root =>	'/var/www/point-one/www/public_html/',
	db_host		=>	'database',
	db_name		=>	'point-one',
	db_user		=>	'point-one',
	db_pass		=>	'point-one',
	site_url		=>	'http://www.point-one.com',
	site_title	=>	'PointOne Graphics Inc',
	log_file		=>	'/var/log/openprint-syslog.log',
	log_level	 =>	'debug',
);

