#!/usr/bin/perl 
use lib '/var/www/testing/perl';
use strict;

require sql;
require sets;
require logger;
require configuration;

use Date::Parse ();
use Date::Calc ();
use Socket ();
require openprint::Host;


use vars qw( $log $dbh %config);
*log = \$openprint::log;
*dbh = \$openprint::dbh;
*config = \%openprint::config;
$log = logger->new();
$log->{level} = 'debug';

use Getopt::Long;
use File::Basename qw(basename);

my $program = basename($0);

my $opts = {};
GetOptions($opts, 'help', 
    'db_name=s', 'db_host=s', 'db_user=s', 'db_pass=s','blacklist=s', 'debug=s',
 );

if ($opts->{help}) {
    usage();
    exit 0;
}

unless ($opts->{db_name}) {
    print STDERR "$program: missing required --db_name parameter\n";
    exit 1;
}
unless ($opts->{db_user}) {
    print STDERR "$program: missing required --db_user parameter\n";
    exit 1;
}
unless ($opts->{db_pass}) {
    print STDERR "$program: missing required --db_pass parameter\n";
    exit 1;
}

configuration::merge( $opts );

$dbh = sql::open_sql( $log,
    'host'      => $opts->{'db_host'},
    'database'  => $opts->{'db_name'},
    'driver'    => 'Pg',
    'login'     => $opts->{'db_user'},
    'password'  => $opts->{'db_pass'},
);
die 'Error opening db' if ! $dbh;


my @log_files = (
	'/var/log/auth.log',
	'/var/log/syslog',
);

my @re = (
'^(\w{3} [ :0-9]{11}) [\._a-zA-Z0-9\-]+ sshd\[[0-9]+\]: pam_\w+\(sshd:auth\): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=([\._a-zA-Z0-9\-]+)\s*$',
'^(\w{3} [ :0-9]{11}) [\._a-zA-Z0-9\-]+ sshd\[[0-9]+\]: pam_\w+\(sshd:auth\): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=([\._a-zA-Z0-9\-]+)\s+user\=\w+$',
'^(\w{3} [ :0-9]{11}) [\._a-zA-Z0-9\-]+ sshd\[[0-9]+\]: Failed password for [\._a-zA-Z0-9\-]+ from ([\._a-zA-Z0-9\-]+) port [0-9]+ ssh2$',
'^(\w{3} [ :0-9]{11}) [\._a-zA-Z0-9\-]+ sshd\[[0-9]+\]: Failed password for illegal user [\._a-zA-Z0-9\-]+ from ([\._a-zA-Z0-9\-]+) port [0-9]+ ssh2$',
'^(\w{3} [ :0-9]{11}) [\._a-zA-Z0-9\-]+ sshd\[[0-9]+\]: error: PAM: Authentication failure for illegal user root from ([\._a-zA-Z0-9\-]+)$',
'^(\w{3} [ :0-9]{11}) [\._a-zA-Z0-9\-]+ sshd\[[0-9]+\]: error: PAM: Authentication failure for [\._a-zA-Z0-9\-]+ from ([\._a-zA-Z0-9\-]+)$',
'^(\w{3} [ :0-9]{11}) [\._a-zA-Z0-9\-]+ sshd\[[0-9]+\]: error: PAM: 1 more authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=([\._a-zA-Z0-9\-]+)\s+user\=\w+$',
'^(\w{3} [ :0-9]{11}) [\._a-zA-Z0-9\-]+ sshd\[[0-9]+\]: Invalid user \w+ from ([0-9.]+)$',
'^(\w{3} [ :0-9]{11}) [\._a-zA-Z0-9\-]+ sshd\[[0-9]+\]: Connection closed by ([0-9.]+):? \[preauth\]$',
'^(\w{3} [ :0-9]{11}) [\._a-zA-Z0-9\-]+ sshd\[[0-9]+\]: Received disconnect from ([0-9.]+) 11: (Bye Bye|PECL/ssh2 \(http://pecl.php.net/packages/ssh2\)) \[preauth\]$',
'^(\w{3} [ :0-9]{11}) [\._a-zA-Z0-9\-]+ sshd\[[0-9]+\]: Received disconnect from ([\.0-9]+): 3: com.jcraft.jsch.JSchException: reject HostKey: [\.0-9]+ \[preauth\]$',
'^(\w{3} [ :0-9]{11}) [\._a-zA-Z0-9\-]+ sshd\[[0-9]+\]: User \w+ from ([0-9.]+) not allowed because not listed in AllowUsers$',
'^(\w{3} [ :0-9]{11}) [\._a-zA-Z0-9\-]+ sshd\[[0-9]+\]: User \w+ from ([0-9.]+) not allowed because account is locked$',
'^(\w{3} [ :0-9]{11}) [\._a-zA-Z0-9\-]+ proftpd\[[0-9]+\]: [\.\-A-Za-z0-9]+ \([\.\-A-Za-z0-9]+\[([.:a-zA-Z0-9]+)\]\) \- Maximum login attempts \([0-9]+\) exceeded, connection refused$',
'^(\w{3} [ :0-9]{11}) [\._a-zA-Z0-9\-]+ proftpd\[[0-9]+\]: [\.\-A-Za-z0-9]+ \([\.\-A-Za-z0-9]+\[([.:a-zA-Z0-9]+)\]\) \- USER "?[\.\-A-Za-z0-9]+"?: no such user found from [0-9.]+\[[0-9.]+\] to [.:a-zA-Z0-9]+$',
'^(\w{3} [ :0-9]{11}) [\._a-zA-Z0-9\-]+ sshd\[[0-9]+\]: Failed keyboard-interactive/pam for invalid user [\.\-A-Za-z0-9]+ from ([.:a-zA-Z0-9]+) port [0-9]+ ssh2$',
'^(\w{3} [ :0-9]{11}) [\._a-zA-Z0-9\-]+ dovecot: pop3-login: Disconnected \(auth failed, 1 attempts\): user=<[a-zA-Z@\.0-9]*>, method=PLAIN, rip=([\.0-9]+), lip=[\.0-9]+(, session=<[^>]+)?$',
q`^(\w{3} [ :0-9]{11}) [\._a-zA-Z0-9\-]+ named\[[0-9]+\]: client ([0-9.]+)#[0-9]+: query \(cache\) '\./NS/IN' denied$`,
);

my $ac = sql::start_transaction( $dbh );
#$dbh->do( 'LOCK TABLE Hosts IN ACCESS EXCLUSIVE MODE' ) or $log->error( DBI->errstr );
my %host_counts;
my @whitelist = map{ $_->ip() } openprint::Host_Interface->find('whitelist'=>1,'ip is null'=>0);

foreach my $log_file ( @log_files ) {
	if ( open( FH, "<$log_file" ) ) {
		foreach my $line (<FH>) {
			foreach my $re ( @re ) {
print "Trying $re against $line\n" if $opts->{debug};
				if ( $line =~ /$re/ ) {
					my ($when, $source ) = ( $1, $2 );
					print "match for $source\n" if $opts->{debug};
					my ( $ip, $hostname );
					if ( $source =~ /^\d+\.\d+\.\d+\.\d+$/ ) {
						# Is an IP
						print "$source is an ip\n" if $opts->{debug};
						$ip = $source;
					} else {
						# is a hostname
						$hostname = $source;
						$ip = gethostbyname($source);
						if ( defined $ip ) {
							$ip = Socket::inet_ntoa($ip);
							print "Got $ip for $source\n" if $opts->{debug};
						} # end if
					} # end if

					next if $ip eq '127.0.0.1';
					
					if ( $ip and @whitelist and sets::isin( $ip, \@whitelist ) ) {
						print "$ip is whitelisted\n" if $opts->{debug};
						next;
					} # end if
					if ( ! $ip ) {
						print "No ip for $source\n" if $opts->{debug};
						next;
					} # end if

					if ( ! $host_counts{$ip} ) {
						my $Host = openprint::Host->find_one(ip=>$ip);
						if ( $Host ) {
							$host_counts{$$Host{ip}} = $Host;
						} else {
							$host_counts{$ip} = new openprint::Host();
							$host_counts{$ip}->ip( $ip );
							$host_counts{$ip}->hostname( $hostname );
						} # end if
					} # end if
					my $last_seen = Date::Parse::str2time( $host_counts{$ip}{updated_on} ) if $host_counts{$ip} and $host_counts{$ip}{updated_on};;
					my $occurrence = Date::Parse::str2time( $when );
#$log->warn("Last: $host_counts{$ip}{updated_on} => $last_seen, $when => $occurrence") if $host_counts{$ip};
					if ( (!$last_seen) or ($last_seen < $occurrence) ) {
						$host_counts{$ip}{'count'} += 1;
						$host_counts{$ip}{'update'} = 1;
					} else {
						print "Not counting because too old " . $host_counts{$ip}{updated_on} . " >= $when" if $opts->{debug};	
					} # end if
					last;
				} # end if line matches re
			} # end foreach re
		} # end if
		close( FH );
	} # end if
} # end foreach

foreach my $ip ( sort keys %host_counts ) {
	next if ! $host_counts{$ip}{update};
	next if $host_counts{$ip}{whitelist};
	if ( $host_counts{$ip}{count} > 20 ) { 
		$host_counts{$ip}{blacklist}=1;
	} # end if
	$_ = $host_counts{$ip}->save();
	if ( $_ ) {
		print $_ . "\n";
	} # end if
	print "$ip $host_counts{$ip}{ip} $host_counts{$ip}{count}\n" if $opts->{debug};
} # end foreach ip
sql::end_transaction( $dbh, $ac );

if ( $opts->{'blacklist'} ) {
	if ( ! open( FH, '>'.$opts->{'blacklist'} ) ) {
		die 'Unable to open blacklist: ' . $opts->{'blacklist'} . "\n";
	} else {
		foreach my $Host ( openprint::Host->find('blacklist'=>1,'order'=>'ip') ) {
			my $macs = $Host->mac();
			if ( $macs and @{$macs} ) {
				foreach my $mac ( @{$macs} ) {
					$mac =~ s/:/\-/g;
					print FH "~$mac\n";
				} # end foreach mac
			} elsif ( $Host->ip() ) {
				print FH $Host->ip()."\n";
			} # end if
		} # end foreach Host
		close(FH);
	} # end if
	`/etc/init.d/shorewall restart`;
} else {
	foreach my $Host ( openprint::Host->find('blacklist'=>1,'order'=>'ip') ) {
		my $macs = $Host->mac();
		if ( $macs and @{$macs} ) {
			foreach my $mac ( @{$macs} ) {
				$mac =~ s/:/\-/g;
				`/sbin/shorewall drop ~$mac`;
			} # end foreach mac
		} elsif ( $Host->ip() ) {
			`/sbin/shorewall drop $$Host{ip}`;
		} # end if
	} # end foreach Host
} # end if

sub usage {
	print <<EOH;

usage: logcheck [--help] 

The purpose of this script is to monitor the AuthLog looking for attacks.

Command-line options:

	--help		Displays this message.

EOH
} # end sub usage

1;
__END__
