#!/usr/bin/perl
use lib '/etc/apache2/lib/perl';

use sql;

use strict;
use Socket;
use Date::Parse;

require logger;

use vars qw( $log $dbh %config);
*log = \$openprint::log;
*dbh = \$openprint::dbh;
#*config = \%openprint::config;
$log = logger->new();
$log->{level} = "warn";

use Getopt::Long;
use File::Basename qw(basename);

my $program = basename($0);

my $opts = {};
GetOptions($opts, 'help', 
    'db_name=s', 'db_host=s', 'db_user=s', 'db_pass=s','blacklist=s',
 );

if ($opts->{help}) {
    usage();
    exit 0;
}

unless ($opts->{db_name}) {
    print STDERR "$program: missing required --db_name parameter\n";
    exit 1;
}
unless ($opts->{db_user}) {
    print STDERR "$program: missing required --db_user parameter\n";
    exit 1;
}
unless ($opts->{db_pass}) {
    print STDERR "$program: missing required --db_pass parameter\n";
    exit 1;
}

$dbh = sql::open_sql( $log,
    'host'      => $opts->{'db_host'},
    'database'  => $opts->{'db_name'},
    'driver'    => 'Pg',
    'login'     => $opts->{'db_user'},
    'password'  => $opts->{'db_pass'},
);
die 'Error opening db' if ! $dbh;


my @log_files = (
	'/var/log/auth.log',
);

my @re = (
'^(\w{3} [ :0-9]{11}) [\._a-zA-Z0-9\-]+ sshd\[[0-9]+\]: pam_unix\(sshd:auth\): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=([\._a-zA-Z0-9\-]+)\s*$',
'^(\w{3} [ :0-9]{11}) [\._a-zA-Z0-9\-]+ sshd\[[0-9]+\]: pam_unix\(sshd:auth\): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=([\._a-zA-Z0-9\-]+)\s+user\=\w+$',

);

my %host_counts;

foreach my $log_file ( @log_files ) {
	if ( open( FH, "<$log_file" ) ) {
		foreach my $line (<FH>) {
			foreach my $re ( @re ) {
#print "Trying \n$re against\n $line\n" if $line =~ /authen/;
				if ( $line =~ /$re/ ) {
					my ($when, $source ) = ( $1, $2 );
					#print "match for $source\n";
					my $ip;
					if ( $source =~ /^\d+\.\d+\.\d+\.\d+$/ ) {
						# Is an IP
						$ip = $source;
					} else {
						# is a hostname
						$ip = gethostbyname($source);
						if ( defined $ip ) {
							$ip = inet_ntoa($ip);
							#print "Got $ip for $source\n";
						} # end if
					} # end if
					next if $ip =~ /^209\.250\.156/;
					next if $ip =~ /^173\.34\.14\.197/;
					if ( ! $ip ) {
						print "No ip for $source\n";
					} else {
						if ( ! $host_counts{$ip} ) {
							$host_counts{$ip} = $openprint::dbh->selectrow_hashref( 'SELECT * FROM blacklist WHERE ip=?', {}, $ip );
						} # end if
						my $last_seen = Date::Parse::str2time( $host_counts{$ip}{updated_on} ) if $host_counts{$ip};
						my $occurrence = Date::Parse::str2time( $when );
$log->warn("Last: $host_counts{$ip}{updated_on} => $last_seen, $when => $occurrence") if $host_counts{$ip};
						if ( (!$last_seen) or ($last_seen < $occurrence) ) {
							$host_counts{$ip}{'count'} += 1;
							$host_counts{$ip}{'update'} = 1;
						} # end if
					} # end if
					last;
				} # end if line matches re
			} # end foreach re
		} # end if
		close( FH );
	} # end if
} # end foreach

foreach my $ip ( sort keys %host_counts ) {
	next if ! $host_counts{$ip}{'update'};
	if ( $host_counts{$ip}{'ip'} ) {
		if ( my $e = sql::update( undef, undef, 'blacklist',['ip=?',$ip], ['updated_on', 'NOW()', 'count', $host_counts{$ip}{'count'}] ) ) {
			print $e . "\n";
		} # end if
	} else {
		if ( my $e = sql::insert( undef, undef, 'blacklist',['ip',$ip, 'updated_on', 'NOW()', 'count', $host_counts{$ip}{'count'}] ) ) {
			print $e . "\n";
		} # end if
	} # end if
	print "$ip $host_counts{$ip}{ip} $host_counts{$ip}{count}\n";
} # end foreach ip

if ( $opts->{'blacklist'} ) {
	if ( ! open( FH, '>'.$opts->{'blacklist'} ) ) {
		die 'Unable to open blacklist: ' . $opts->{'blacklist'} . "\n";
	} else {
		foreach my $ip ( sql::execute( undef, undef, q`SELECT ip FROM blacklist WHERE updated_on > NOW()-'1 month'::interval AND count > 10 ORDER BY ip` ) ) {
			print FH "$ip\n";
		} # end foreach ip
		close(FH);
	} # end if
	`/etc/init.d/shorewall restart`;
} # end if

sub usage {
	print <<EOH;

usage: logcheck [--help] 

The purpose of this script is to monitor the AuthLog looking for attacks.

Command-line options:

	--help		Displays this message.

EOH
} # end sub usage

1;
__END__
