DROP TABLE IF EXISTS Expense_Rules;

CREATE TABLE Expense_Rules (
  id serial,
  name  TEXT,
  rules_json  JSON,
  action_json JSON,
  category_id INTEGER, FOREIGN KEY (category_id) REFERENCES Expense_Rule_Categories (id),
  created_on TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_on TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);

INSERT INTO Expense_Rules (name,rules_json,action_json) VALUES 
( 'Certas', '[{"desc": "/^CERTAS H & A\\s+(?<transaction_id>.+)$/"}]','{
  "category":"Insurance",
  "recipient":"Certas Home and Auto Insurance",
  "transaction_id":"$$self{matches}{transaction_id}"}'),
( 'Rogers', '[{"desc": "/^RGRS 9 DIGIT\\s+(?<transaction_id>.+)$/"}]', '{"category":"Utilities","recipient":"ROGERS Wireless",
  "transaction_id":"$$self{matches}{transaction_id}"}'),
( 'LCBO', '[{"desc":"/^LCBO/"}]', '{"category": "Alcohol","recipient":"LCBO"}'),
( 'Enbridge', '[{"desc": "/^ENBRIDGE/"}]','{"category": "Utilities - Gas", "recipient":"Enbridge"}'),
( 'Telus', '[{"desc": "/Telus Mobility/"}]','{"category" : "Utilities", "recipient":"TELUS Mobility"}'),
( 'ODP', '[{"desc":"/O.D.P. FEE/"}]', '{"category": "Service Charges", "recipient":"TD Canada Trust"}'),
( 'WITHDRAWAL FEES', '[{"desc": "/WITHDRAWAL FEES/"}]','{"category": "Service Charges", "recipient":"TD Canada Trust"}'),
( 'MONTHLY PLAN FEE', '[{"desc": "/^MONTHLY PLAN FEE/"}]','{"category": "Service Charges", "recipient":"TD Canada Trust"}'),
( 'TAX PYT FEE', '[{"desc": "/^TAX PYT FEE/"}]','{"category": "Service Charges", "recipient":"TD Canada Trust"}'),
( 'SMALL BUS LN FEE', '[{"desc": "/^SMALL BUS LN FEE/"}]','{"category": "Service Charges", "recipient":"TD Canada Trust"}'),
( 'NSF PAID FEE', '[{"desc": "/^NSF PAID FEE/"}]','{"category": "Service Charges", "recipient":"TD Canada Trust"}'),
( 'BUS LINE FEE', '[{"desc": "/^BUS LINE FEE/"}]','{"category": "Service Charges", "recipient":"TD Canada Trust"}'),
( 'OVERDRAFT INTEREST', '[{"desc": "/^OVERDRAFT INTEREST/"}]','{"category": "Interest", "recipient":"TD Canada Trust"}'),
( 'PRODUCT PROTECTOR', '[{"desc": "/^PRODUCT PROTECTOR/"}]','{"category": "Service Charge", "recipient":"Mastercard"}'),
( 'PURCHASE INTEREST CHARGE', '[{"desc": "/^PURCHASE INTEREST CHARGE/"}]','{"category": "Interest", "recipient":"Mastercard"}'),
('CIBC Purchase Interest', '[{"desc":"/^PURCHASE INTEREST$/"}]', '{"category":"Interest","recipient":"CIBC"}'),
('CIBC Cash Interest', '[{"desc":"/^CASH INTEREST$/"}]', '{"category":"Interest","recipient":"CIBC"}'),
('CIBC Cash Advance', '[{"desc":"/^CASH ADV/BT/CONV CHQ FEE$/"}]', '{"category":"Service Charge","recipient":"CIBC"}'),
('Intuit', '[{"desc":"/^INTUIT CANADA/"}]', '{"category":"Business Expense","recipient":"Intuit"}'),
('CIBC VISA Payment', '[{"desc":"/^CIBC VISA/"}]', '{"category":"Transfer","recipient":"CIBC"}'),
( 'PURCHASE \\*FINANCE CHARGE\\*', '[{"desc": "/^PURCHASE \\*FINANCE CHARGE\\*/"}]','{"category": "Interest", "recipient":"Mastercard"}'),
( 'MXTOOLBOX', '[{"desc": "/^MXTOOLBOX/"}]','{"category": "Business Expense", "recipient":"MxToolBox"}'),
( 'PAPER STMT FEE', '[{"desc": "/^PAPER STMT FEE/"}]','{"category": "Service Charges", "recipient":"TD Canada Trust"}'),
( 'Fusion', '[{"desc": "/^FUSION CHIROPRA/"}]','{"category": "Medical", "recipient":"FUSION CHIROPRACTIC"}'),
( 'Foodland', '[{"desc": "/^FOODLAND/"}]','{"category": "Food", "recipient":"Foodland"}'),
( 'Loblaws', '[{"desc": "/^LOBLAWS/"}]','{"category": "Food", "recipient":"Loblaws"}'),
( 'Sobeys', '[{"desc": "/^SOBEYS/"}]','{"category": "Food", "recipient":"Sobeys"}'),
( 'ESSO', '[{"desc": "/^ESSO/"}]','{"category": "Gas", "recipient":"Esso"}'),
( 'PETROCAN', '[{"desc": "/^PETROCAN/"}]','{"category": "Gas", "recipient":"Petro-Canada"}'),
( 'PIONEER', '[{"desc": "/^PIONEER/"}]','{"category": "Gas", "recipient":"Pioneer Energy LP"}'),
( 'MOBIL', '[{"desc": "/^MOBIL/"}]','{"category": "Gas", "recipient":"Mobil"}'),
('Etransfer', '[{"desc":"/^SEND E\\-TFR (?<transaction_id>.+)$/"} ]', '{"transaction_id":"$$self{matches}{transaction_id}"}'),
('Coinbase', '[{"desc":"/^COINBASE/"}]', '{"category":"Investments - Crypto","recipient":"Coinbase"}'),
('PC Mastercard', '[{"desc":"/^PC MASTRCRD\\s+(?<transaction_id>.+)$/"}]', '{"category":"Credit Card Payment","recipient":"Mastercard","transaction_id":"$$self{matches}{transaction_id}"}'),
('TD Visa', '[{"desc":"/^(?<transaction_id>\\w+) TFR-TO C\/C$/"}]', '{"category":"Credit Card Payment","recipient":"TD Canada Trust","transaction_id":"$$self{matches}{transaction_id}"}'),
('CDN Tire Mastercard', '[{"desc":"/^CAN TIRE MC\\s+(?<transaction_id>.+)$/"}]', '{"category":"Credit Card Payment","recipient":"Mastercard","transaction_id":"$$self{matches}{transaction_id}"}'),
('Toronto Hydro',
  '[{"desc":"/^TOR HYD ELEC\\s+(?<transaction_id>.+)$/"}]', '{"category":"Utility - Electricity","recipient":"Toronto Hydro","transaction_id":"$$self{matches}{transaction_id}"}'),
('Mutual Funds', '[{"desc":"/^TD MUTUAL FUNDS/"}]', '{"category":"Investments - Mutual Funds","recipient":"TD Canada Trust"}'),
('GST', '[{"desc":"/^GST\\-P\\s+(?<transaction_id>\\d+)\\s+BUS/"}]', '{"category":"Taxes","recipient":"CRA","transaction_id":"$$self{matches}{transaction_id}"}'),
('THE GLOBE AND MAIL', '[{"desc":"/^THE GLOBE AND MAIL/"}]', '{"category":"Subscriptions","recipient":"Globe And Mail"}'),
('DE LA MER FRESH FISH M', '[{"desc":"/^DE LA MER FRESH FISH M/"}]', '{"category":"Food","recipient":"De La Mer"}'),
('SKIPTHEDISHES.COM', '[{"desc":"/^SKIPTHEDISHES\\.COM/"}]', '{"category":"Food","recipient":"SkipTheDishes"}'),
('Burger King', '[{"desc":"/^BK #/"}]', '{"category":"Food","recipient":"Burger King"}'),
('DAVE AND CHARLOTTE', '[{"desc":"/^DAVE AND CHARLO/"}]', '{"category":"Food","recipient":"NO FRILLS"}'),
('Rebel.ca', '[{"desc":"/^REBEL\\.CA CORP/"}]', '{"category":"Business Expense","recipient":"Rebelca"}'),
('Queen St Dental', '[{"desc":"/^QUEEN STREET DE/"}]', '{"category":"Medical - Dentist","recipient":"Queen Street Dental"}'),
('Postables', '[{"desc":"/^POSTABLES/"}]', '{"category":"Shipping","recipient":"Postables"}'),
('Toronto Parking', '[{"desc":"/^TORONTO PARKING AUTHOR/"}]', '{"category":"Parking","recipient":"Toronto Parking Authority"}');
