DROP TABLE IF EXISTS hosts CASCADE;
CREATE TABLE hosts (
	id			SERIAL,
	hostname	text,
	name	text,
	abbr_name	text,
	blacklist	boolean not null default false,
	whitelist	boolean not null default false,
	monitored	boolean not null default false,
	description text,
	dhcp		boolean not null default false,
	created_on	TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	updated_on	TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	resolved_on	TIMESTAMP WITH TIME ZONE,
	count		INTEGER,
	deleted		BOOLEAN NOT NULL DEFAULT FALSE,
	online		BOOLEAN,
	state_changed_on	INTEGER,
	offline_seconds		INTEGER,
	notified			BOOLEAN NOT NULL DEFAULT FALSE,
	notify_frequency	INTEGER,
	location_id			INTEGER, FOREIGN KEY (location_id) REFERENCES Locations (id),
	owner_id			INTEGER, FOREIGN KEY (owner_id) REFERENCES Companies (id),
	type_id INTEGER, FOREIGN KEY (type_id) REFERENCES Host_types (id),
  min_ping_frequency  INTEGER,
  max_ping_time       INTEGER,
	PRIMARY KEY (id)
);
