DROP TABLE IF EXISTS Orders;

CREATE TABLE Orders (
	id		SERIAL,
	company_id	INTEGER NOT NULL, FOREIGN KEY (company_id) REFERENCES companies (id),
	user_id		INTEGER NOT NULL, FOREIGN KEY (user_id) REFERENCES Users (id),
	salesrep_id	INTEGER, FOREIGN KEY (salesrep_id) REFERENCES Users (id),
	curFedTax		NUMERIC(10,2),
	curHarmTax		NUMERIC(10,2),
	curProvTax		NUMERIC(10,2),
	curTotalSale	NUMERIC(20,2),
	curDownpayment	NUMERIC(20,2),
	dtmOrderDate	timestamp with time zone NOT NULL,
	dtmRequiredDate	timestamp with time zone,
	dtmShipDate		timestamp with time zone,
	lngShipVia		INT2,		/* Reference into tbl_ShipVia */
	strShippingTracking	TEXT,
	curFreight		NUMERIC(18,4) DEFAULT '0.0000' NOT NULL,
	ysnFinished		CHAR(1) DEFAULT 'N' NOT NULL,				/* Signifies whether order has been MADE not whether its been filled */
	strPONumber		TEXT,
	strAccountNum	TEXT,
	strCompanyName	TEXT,
	strFirstName			TEXT,
	strLastName				TEXT,
	strTitle				TEXT,
	strSalutation			TEXT,
	strAddress1				TEXT,
	strAddress2				TEXT,
	strCity					TEXT,
	strState				TEXT,
	strCountry				TEXT,
	strPostalCode			TEXT,
	strPhone				TEXT,
	strExt					TEXT,
	strFax					TEXT,
	strEmail				TEXT,
	strShippingCompanyName	TEXT,
	strShippingFirstName	TEXT,
	strShippingLastName		TEXT,
	strShippingTitle		TEXT,
	strShippingSalutation	TEXT,
	strShippingAddress1		TEXT,
	strShippingAddress2		TEXT,
	strShippingCity			TEXT,
	strShippingState		TEXT,
	strShippingCountry		TEXT,
	strShippingPostalCode	TEXT,
	strShippingPhone		TEXT,
	strShippingExt			TEXT,
	strShippingFax			TEXT,
	strShippingEmail		TEXT,
	strAlsoNotify			TEXT,
	strStatus				TEXT,
	dblShippingCost			NUMERIC(10,2),
	CurrencyIndex			INTEGER, FOREIGN KEY (CurrencyIndex) REFERENCES Currencies (id),
	strCurrencyName			TEXT,
	strCurrencySymbol		char(1),
	strComments				TEXT,
	strAdministratorComments	TEXT,
	strAdministratorName		TEXT,
	docket			INTEGER,
	strsessionid			TEXT,
	invoice_id				INTEGER, FOREIGN KEY (invoice_id) REFERENCES invoices(id),
	PRIMARY KEY (id)
);
