DROP TABLE IF EXISTS RSS;

CREATE TABLE RSS (
	id	SERIAL,
	name	TEXT,
	url		TEXT,
	created_on	TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	updated_on	TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	scan_interval	INTERVAL,
	next_scan	TIMESTAMP WITH TIME ZONE,
	last_scanned TIMESTAMP WITH TIME ZONE,
	PRIMARY KEY (id)
);
