CREATE TABLE WorkOrders (
  id SERIAL,
  company_id INTEGER NOT NULL DEFAULT 0,
  status_id INTEGER, FOREIGN KEY (status_id) REFERENCES WorkOrder_Statuses (id),
  RMANumber TEXT,
  PONumber TEXT,
  WInvoice TEXT,
  received_on TIMESTAMP WITH TIME ZONE,
  UnitName TEXT,
  serialnumber TEXT,
  Accessories TEXT,
  Priority TEXT,
  Warranty TEXT,
  estimate_required TEXT,
  Remarks TEXT,
  environmental_test TEXT,
  customer_problem TEXT,
  area_of_defect TEXT,
  DateRepaired TIMESTAMP WITH TIME ZONE,
  new_coefficient TEXT,
  Bias TEXT,
  time_spent TEXT,
  Comments TEXT,
  PartsID INTEGER DEFAULT 0,
  ShipperName TEXT,
  ShippedDate TIMESTAMP WITH TIME ZONE,
  PreparedDate TIMESTAMP WITH TIME ZONE,
  RepairedBy TEXT,
  tester TEXT,
  ShippedViaID INTEGER DEFAULT 0,
  TrackingNo TEXT,
  PackingSlipNo TEXT,
  PRIMARY KEY (id)
) ;

